version: '3.5'

services:
    backend:
      image: backend-final
      environment: 
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_NAME=backend_db
        - DB_HOST=database
      ports:
          - 8000:8000
      restart: unless-stopped
      container_name: backend_node
      depends_on:
        - database
    
    frontend:
      image: frontend-final
      ports:
          - 5000:5000
      container_name: frontend_node
    
    redis:
      image: redis
      container_name: redis_node
    
    database:
      image: postgres
      restart: unless-stopped
      environment:
          - POSTGRES_PASSWORD=example
          - POSTGRES_DB=backend_db
    
    proxy:
      image: nginx
      restart: unless-stopped
      ports:
          - 80:80
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf